# Generated by Django 3.1.2 on 2020-10-01 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeltomove',
            name='new_field',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Something new'),
        ),
    ]
