# Generated by Django 3.1.2 on 2020-10-01 19:42

from django.db import migrations
from move_model import operations


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0002_modeltomove_new_field'),
    ]

    destination_table_name = 'destination_modeltomove'


    operations = [
        operations.MoveModelOut(
            name='ModelToMove',
            table=destination_table_name
        ),
    ]
