# Generated by Django 3.1.2 on 2020-10-01 19:42

from django.db.migrations.operations import RunSQL
from neutered_migration import migrations


class Migration(migrations.NeuteredMigration):

    dependencies = [
        ('origin', '0002_modeltomove_new_field'),
    ]

    orgin_table_name = 'origin_modeltomove'
    destination_table_name = 'destination_modeltomove'

    operations = [
        RunSQL(
            sql = [
                "ALTER TABLE {origin} RENAME TO {destination};".format(
                origin=orgin_table_name, destination=destination_table_name),
            ],
            reverse_sql=[
                "ALTER TABLE {destination} RENAME TO {origin};".format(
                    origin=orgin_table_name, destination=destination_table_name),
            ]
        ),
        migrations.DeleteModel(
            name='ModelToMove',
        ),
    ]
