# Generated by Django 3.1.2 on 2020-10-01 19:42

from django.db import migrations, models
from move_model import operations

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        operations.MoveModelIn(
            name='ModelToMove',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('data', models.IntegerField(default=42, verbose_name='A piece of data')),
                ('new_field', models.CharField(blank=True, default='', max_length=100, verbose_name='Something new')),
            ],
        ),
    ]
